/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c yowsup_main -p yowsup_main.h:yowsup_main.cpp com.yowsup.methods.xml com.yowsup.methods
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "yowsup_main.h"

/*
 * Implementation of interface class yowsup_main
 */

yowsup_main::yowsup_main(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

yowsup_main::~yowsup_main()
{
}

