/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c yowsup_methods -p yowsup_methods.h:yowsup_methods.cpp com.yowsup.0.methods.xml com.yowsup.methods
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "yowsup_methods.h"

/*
 * Implementation of interface class yowsup_methods
 */

yowsup_methods::yowsup_methods(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

yowsup_methods::~yowsup_methods()
{
}

