/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c yowsup_signals -p yowsup_signals.h:yowsup_signals.cpp com.yowsup.0.signals.xml com.yowsup.signals
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "yowsup_signals.h"

/*
 * Implementation of interface class yowsup_signals
 */

yowsup_signals::yowsup_signals(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

yowsup_signals::~yowsup_signals()
{
}

