/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c yowsup_signals -p yowsup_signals.h:yowsup_signals.cpp com.yowsup.0.signals.xml com.yowsup.signals
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef YOWSUP_SIGNALS_H_1361953676
#define YOWSUP_SIGNALS_H_1361953676

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.yowsup.signals
 */
class yowsup_signals: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.yowsup.signals"; }

public:
    yowsup_signals(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~yowsup_signals();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> getSignals()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getSignals"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void audio_received(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
    void auth_fail(const QString &username, const QString &reason);
    void auth_success(const QString &username);
    void contact_gotProfilePicture(const QDBusVariant &jid, const QDBusVariant &filename);
    void contact_gotProfilePictureId(const QDBusVariant &jid, const QDBusVariant &pictureId);
    void contact_paused(const QDBusVariant &jid);
    void contact_typing(const QDBusVariant &jid);
    void disconnected(const QDBusVariant &reason);
    void group_addParticipantsSuccess(const QDBusVariant &jid);
    void group_audioReceived(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
    void group_createFail(const QDBusVariant &errorCode);
    void group_createSuccess(const QDBusVariant &jid, const QDBusVariant &group_id);
    void group_endSuccess(const QDBusVariant &jid);
    void group_gotInfo(const QDBusVariant &jid, const QDBusVariant &owner, const QDBusVariant &subject, const QDBusVariant &subjectOwner, const QDBusVariant &subjectT, const QDBusVariant &creation);
    void group_gotParticipants(const QDBusVariant &jid, const QDBusVariant &jids);
    void group_gotPicture(const QDBusVariant &jid, const QDBusVariant &filepath);
    void group_imageReceived(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &preview, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
    void group_infoError(const QDBusVariant &errorCode);
    void group_locationReceived(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &name, const QDBusVariant &preview, const QDBusVariant &latitude, const QDBusVariant &longitude, const QDBusVariant &wantsReceipt);
    void group_messageReceived(const QDBusVariant &msgId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &content, const QDBusVariant &timestamp, const QDBusVariant &wantsReceipt);
    void group_removeParticipantsSuccess(const QDBusVariant &jid);
    void group_setPictureError(const QDBusVariant &jid, const QDBusVariant &errorCode);
    void group_setPictureSuccess(const QDBusVariant &jid);
    void group_setSubjectSuccess(const QDBusVariant &jid);
    void group_subjectReceived(const QDBusVariant &msgId, const QDBusVariant &fromAttribute, const QDBusVariant &author, const QDBusVariant &newSubject, const QDBusVariant &timestamp, const QDBusVariant &receiptRequested);
    void group_vcardReceived(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &name, const QDBusVariant &data, const QDBusVariant &wantsReceipt);
    void group_videoReceived(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &preview, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
    void image_received(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &preview, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
    void location_received(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &name, const QDBusVariant &preview, const QDBusVariant &latitude, const QDBusVariant &longitude, const QDBusVariant &wantsReceipt);
    void message_error(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &errorCode);
    void message_received(const QDBusVariant &msgId, const QDBusVariant &jid, const QDBusVariant &content, const QDBusVariant &timestamp, const QDBusVariant &wantsReceipt);
    void notification_contactProfilePictureUpdated(const QDBusVariant &jid, const QDBusVariant &timestamp, const QDBusVariant &messageId, const QDBusVariant &wantsReceipt);
    void notification_groupParticipantAdded(const QDBusVariant &gJid, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &timestamp, const QDBusVariant &messageId, const QDBusVariant &wantsReceipt);
    void notification_groupParticipantRemoved(const QDBusVariant &gjid, const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &timestamp, const QDBusVariant &messageId, const QDBusVariant &wantsReceipt);
    void notification_groupPictureUpdated(const QDBusVariant &jid, const QDBusVariant &author, const QDBusVariant &timestamp, const QDBusVariant &messageId, const QDBusVariant &wantsReceipt);
    void ping(const QDBusVariant &pingId);
    void pong();
    void presence_available(const QDBusVariant &jid);
    void presence_unavailable(const QDBusVariant &jid);
    void presence_updated(const QDBusVariant &jid, const QDBusVariant &lastSeen);
    void profile_setPictureError(const QDBusVariant &errorCode);
    void profile_setPictureSuccess();
    void profile_setStatusSuccess(const QDBusVariant &jid, const QDBusVariant &messageId);
    void receipt_messageDelivered(const QDBusVariant &jid, const QDBusVariant &msgId);
    void receipt_messageSent(const QDBusVariant &jid, const QDBusVariant &msgId);
    void receipt_visible(const QDBusVariant &jid, const QDBusVariant &msgId);
    void status_dirty();
    void vcard_received(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &name, const QDBusVariant &data, const QDBusVariant &wantsReceipt);
    void video_received(const QDBusVariant &messageId, const QDBusVariant &jid, const QDBusVariant &preview, const QDBusVariant &url, const QDBusVariant &size, const QDBusVariant &wantsReceipt);
};

#endif
