/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -c yowsup_main -p yowsup_main.h:yowsup_main.cpp com.yowsup.methods.xml com.yowsup.methods
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef YOWSUP_MAIN_H_1362113365
#define YOWSUP_MAIN_H_1362113365

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.yowsup.methods
 */
class yowsup_main: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.yowsup.methods"; }

public:
    yowsup_main(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~yowsup_main();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> init(const QString &username)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(username);
        return asyncCallWithArgumentList(QLatin1String("init"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
